import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

import Banner from "../components/banner.jsx";

export default function Home() {

  const handleBannerClick = (e) => {
    console.log(e);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner handleClick={handleBannerClick} buttonText="View stores nearby" />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
}
